# # Use Node.js official image
# FROM node:alpine

# # Set working directory
# WORKDIR /app

# # Copy package.json and install dependencies
# COPY package*.json ./
# RUN npm install

# # Copy the rest of the code
# COPY . .

# # Expose backend port
# EXPOSE 3000

# # Start server
# CMD ["node", "server.js"]
FROM node:18

WORKDIR /app

COPY server.js .

RUN npm init -y && npm install express cors

EXPOSE 3000

CMD ["node", "server.js"]

